### ISSUE TITLE
unable to import tab delimited file

### ISSUE THREAD

**Issue by budfcusodncfisoda** [linnarsson-lab/ceftools#1]
Hello,
I need to create a '.cef' file for backspin (single cell clustering). I'm trying to convert a tab-separated text file, containing expression data, into a cef file using the following command:

cef import --format "strt" my_expr_data.tab

can you help me figure out what I'm doing wrong?

Thanks,
Lando

**Comment by slinnarsson** [comment]
Hi

The “strt” format is a legacy format we used internally, and not just a simple tab-delimited file. 

But note that .cef _is_ a tab-delimited format. You can easily create cef files in e.g. Excel or exported from R or Python. Just follow the format specification given at the bottom of this page: https://github.com/linnarsson-lab/ceftools

/Sten

## 

Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet 
Unit of Molecular Neurobiology 
Department of Medical Biochemistry and Biophysics 
Scheeles väg 1, 171 77 Stockholm, Sweden
+46 8 52 48 75 77 (office)
+46 70 399 32 06 (mobile)

**Comment by budfcusodncfisoda** [comment]
thank you, I will use excel to create the .cef formatted file
